/* Hireloom Second Brain — Obsidian plugin (desktop).
 * Reads ONLY _brain_api/*.json (generated by second-brain/plugin/refresh.mjs
 * from Hireloom's real files). Never invents data: every tab renders real rows
 * or its exact empty-state string from the spec's binding table. Writes nothing
 * to user-layer files except an optional self-test line in BUILD-LOG.md.
 */
'use strict';

const { Plugin, ItemView, PluginSettingTab, Setting, Notice } = require('obsidian');

const BUILD_STAMP = 'hireloom-brain v0.1.0 · build 2026-06-11.2';
const VIEW_TYPE = 'hireloom-brain-view';
const API_DIR = '_brain_api';

// Canonical kanban order (templates/states.yml)
const STATE_ORDER = ['Evaluated', 'Applied', 'Responded', 'Interview', 'Offer', 'Rejected', 'Discarded', 'SKIP'];

// Exact empty states from the spec's tab-binding contract
const EMPTY = {
  pipeline: 'No applications tracked — paste a job URL or run /career-ops scan',
  queue: 'No ranked pool — run the batch pipeline or paste URLs into data/pipeline.md',
  radar: 'No applied roles awaiting response',
  interviews: 'Nothing in interview stage yet',
  scan: 'Scanner hasn’t run — node engine/scan/scan.mjs',
  patterns: 'Too few outcomes to analyze yet',
  inbox: 'Inbox empty',
};

const TABS = [
  { id: 'pipeline', label: 'Pipeline' },
  { id: 'queue', label: 'Apply Queue' },
  { id: 'radar', label: 'Follow-up Radar' },
  { id: 'interviews', label: 'Interviews' },
  { id: 'scan', label: 'Scan Feed' },
  { id: 'patterns', label: 'Patterns' },
  { id: 'inbox', label: 'Inbox' },
];

class BrainData {
  constructor(app) {
    this.app = app;
    this.cache = new Map();
  }
  invalidate() { this.cache.clear(); }
  async json(name) {
    if (this.cache.has(name)) return this.cache.get(name);
    let value = null;
    try {
      const raw = await this.app.vault.adapter.read(`${API_DIR}/${name}.json`);
      value = JSON.parse(raw);
    } catch (e) {
      value = { missing: true, readError: String(e && e.message || e) };
    }
    this.cache.set(name, value);
    return value;
  }
}

function rowsOrEmpty(el, items, emptyText, renderRow) {
  if (!items || items.length === 0) {
    el.createDiv({ cls: 'hb-empty', text: emptyText });
    return false;
  }
  items.forEach(renderRow);
  return true;
}

const RENDERERS = {
  async pipeline(el, data) {
    const p = await data.json('pipeline');
    const rows = (p && p.rows) || [];
    if (rows.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.pipeline }); return; }
    el.createDiv({ cls: 'hb-meta', text: `${rows.length} applications · source: data/applications.md` });
    const board = el.createDiv({ cls: 'hb-board' });
    for (const state of STATE_ORDER) {
      const inState = rows.filter((r) => r.status === state);
      if (inState.length === 0) continue;
      const col = board.createDiv({ cls: 'hb-col' });
      const h = col.createDiv({ cls: 'hb-col-h' });
      h.createSpan({ text: state });
      h.createSpan({ cls: 'hb-count', text: String(inState.length) });
      for (const r of inState.slice().sort((a, b) => (b.date || '').localeCompare(a.date || ''))) {
        const card = col.createDiv({ cls: 'hb-card', attr: { title: r.notes || '' } });
        card.createDiv({ cls: 'hb-co', text: r.company });
        card.createDiv({ cls: 'hb-role', text: r.role });
        const sub = card.createDiv({ cls: 'hb-sub' });
        sub.createSpan({ text: r.score || '' });
        sub.createSpan({ text: r.date || '' });
        sub.createSpan({ cls: 'hb-num', text: `#${r.num}` });
      }
    }
  },

  async queue(el, data) {
    const q = await data.json('queue');
    if (!q || q.missing || q.error || !q.head || q.head.length === 0) {
      el.createDiv({ cls: 'hb-empty', text: q && q.error ? `${EMPTY.queue} (${q.error})` : EMPTY.queue });
      return;
    }
    el.createDiv({ cls: 'hb-meta', text: `${q.pendingCount} pending of ${q.total} ranked · next rank ${q.nextRank} · source: output/pool-apply-order.json` });
    rowsOrEmpty(el, q.head, EMPTY.queue, (r) => {
      const row = el.createDiv({ cls: 'hb-row' });
      row.createSpan({ cls: 'hb-num', text: `#${r.rank}` });
      row.createSpan({ cls: 'hb-co', text: r.company });
      row.createSpan({ text: r.title });
      row.createSpan({ cls: 'hb-chip', text: r.ats || '' });
      if (r.url) row.createEl('a', { cls: 'hb-link', text: 'open', href: r.url });
    });
  },

  async radar(el, data) {
    const f = await data.json('followups');
    const entries = (f && f.entries) || [];
    const actionable = entries.filter((e) => e.urgency && e.urgency !== 'waiting');
    if (f && f.error) { el.createDiv({ cls: 'hb-empty', text: `${EMPTY.radar} (${f.error})` }); return; }
    if (actionable.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.radar }); return; }
    const m = f.metadata || {};
    el.createDiv({ cls: 'hb-meta', text: `${m.actionable ?? actionable.length} actionable · ${m.overdue ?? '–'} overdue · source: engine/tracker/followup-cadence.mjs` });
    actionable
      .slice()
      .sort((a, b) => (b.daysSinceApplication || 0) - (a.daysSinceApplication || 0))
      .slice(0, 40)
      .forEach((e) => {
        const row = el.createDiv({ cls: 'hb-row' });
        row.createSpan({ cls: `hb-chip${/overdue|urgent/i.test(e.urgency) ? ' hb-hot' : ''}`, text: e.urgency });
        row.createSpan({ cls: 'hb-co', text: e.company });
        row.createSpan({ text: e.role });
        row.createSpan({ cls: 'hb-num', text: `${e.daysSinceApplication}d since apply · follow-ups: ${e.followupCount}${e.nextFollowupDate ? ` · next ${e.nextFollowupDate}` : ''}` });
      });
  },

  async interviews(el, data) {
    const iv = await data.json('interviews');
    const rows = (iv && iv.rows) || [];
    if (rows.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.interviews }); return; }
    el.createDiv({ cls: 'hb-meta', text: `${rows.length} in interview stage · prep library: ${iv.prepDirCount} files in interview-prep/` });
    rows.forEach((r) => {
      const row = el.createDiv({ cls: 'hb-row', attr: { title: r.notes || '' } });
      row.createSpan({ cls: 'hb-co', text: r.company });
      row.createSpan({ text: r.role });
      const chips = row.createSpan();
      (r.prepFiles || []).slice(0, 5).forEach((p) => chips.createSpan({ cls: 'hb-chip', text: p }));
      if ((r.prepFiles || []).length === 0) chips.createSpan({ cls: 'hb-num', text: 'no prep files yet' });
    });
  },

  async scan(el, data) {
    const s = await data.json('scanfeed');
    if (!s || s.missing || !s.recent || s.recent.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.scan }); return; }
    el.createDiv({ cls: 'hb-meta', text: `${s.total} discoveries all-time · newest ${s.lastSeen} · source: data/scan-history.tsv` });
    s.recent.forEach((r) => {
      const row = el.createDiv({ cls: 'hb-row' });
      row.createSpan({ cls: 'hb-num', text: r.first_seen });
      row.createSpan({ cls: 'hb-co', text: r.company });
      row.createSpan({ text: r.title });
      row.createSpan({ cls: 'hb-chip', text: r.portal });
      if (r.url) row.createEl('a', { cls: 'hb-link', text: 'open', href: r.url });
    });
  },

  async patterns(el, data) {
    const p = await data.json('patterns');
    if (!p || p.error || !p.metadata || !p.metadata.total) { el.createDiv({ cls: 'hb-empty', text: EMPTY.patterns }); return; }
    const m = p.metadata;
    el.createDiv({ cls: 'hb-meta', text: `${m.total} analyzed (${m.dateRange.from} → ${m.dateRange.to}) · source: engine/tracker/analyze-patterns.mjs` });
    el.createDiv({ cls: 'hb-section-h', text: 'Outcomes' });
    const out = m.byOutcome || {};
    const total = Object.values(out).reduce((a, b) => a + b, 0) || 1;
    Object.entries(out).forEach(([k, v]) => {
      const row = el.createDiv({ cls: 'hb-row' });
      row.createSpan({ cls: 'hb-co', text: k });
      row.createSpan({ cls: 'hb-num', text: String(v) });
      row.createDiv({ cls: 'hb-bar', attr: { style: `width:${Math.max(2, Math.round((v / total) * 240))}px` } });
    });
    if (Array.isArray(p.recommendations) && p.recommendations.length) {
      el.createDiv({ cls: 'hb-section-h', text: 'Recommendations' });
      p.recommendations.slice(0, 8).forEach((r) => {
        el.createDiv({ cls: 'hb-row', text: typeof r === 'string' ? r : (r.text || r.message || JSON.stringify(r)) });
      });
    }
  },

  async inbox(el, data) {
    const i = await data.json('inbox');
    const pending = (i && i.pending) || [];
    if (pending.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.inbox }); return; }
    el.createDiv({ cls: 'hb-meta', text: `${i.pendingCount} pending · source: data/pipeline.md` });
    pending.forEach((u) => {
      const row = el.createDiv({ cls: 'hb-row' });
      if (/^https?:/.test(u)) row.createEl('a', { cls: 'hb-link', text: u, href: u });
      else row.createSpan({ text: u });
    });
  },
};

class BrainView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.activeTab = 'pipeline';
  }
  getViewType() { return VIEW_TYPE; }
  getDisplayText() { return 'Hireloom Brain'; }
  getIcon() { return 'layout-dashboard'; }

  async onOpen() { await this.render(); }

  async render() {
    const root = this.contentEl;
    root.empty();
    root.addClass('hb-root');
    const tabs = root.createDiv({ cls: 'hb-tabs' });
    const counts = await this.plugin.tabCounts();
    for (const t of TABS) {
      const tab = tabs.createDiv({ cls: `hb-tab${t.id === this.activeTab ? ' is-active' : ''}` });
      tab.createSpan({ text: t.label });
      if (counts[t.id] != null) tab.createSpan({ cls: 'hb-count', text: String(counts[t.id]) });
      tab.onClickEvent(() => { this.activeTab = t.id; this.render(); });
    }
    const actions = tabs.createDiv({ cls: 'hb-actions' });
    const refreshBtn = actions.createEl('button', { cls: 'hb-btn', text: '↻ refresh data' });
    refreshBtn.onClickEvent(() => this.plugin.runRefresh());
    const body = root.createDiv();
    await RENDERERS[this.activeTab](body, this.plugin.data);
  }
}

module.exports = class HireloomBrain extends Plugin {
  async onload() {
    this.data = new BrainData(this.app);
    this.settings = Object.assign({ }, await this.loadData());

    this.registerView(VIEW_TYPE, (leaf) => new BrainView(leaf, this));
    this.addRibbonIcon('layout-dashboard', 'Hireloom Brain', () => this.activate());

    this.addCommand({ id: 'open', name: 'Open dashboard', callback: () => this.activate() });
    this.addCommand({ id: 'refresh', name: 'Refresh data now', callback: () => this.runRefresh() });
    this.addCommand({ id: 'self-test', name: 'Run self-test', callback: () => this.selfTest() });

    this.addSettingTab(new BrainSettings(this.app, this));

    // Debounced re-render when the machine layer (or tracker) changes.
    let timer = null;
    const onFsEvent = (file) => {
      const p = (file && file.path) || '';
      if (!p.startsWith(`${API_DIR}/`) && !p.startsWith('data/')) return;
      clearTimeout(timer);
      timer = setTimeout(() => {
        this.data.invalidate();
        this.app.workspace.getLeavesOfType(VIEW_TYPE).forEach((l) => l.view && l.view.render && l.view.render());
      }, 400);
    };
    this.registerEvent(this.app.vault.on('modify', onFsEvent));
    this.registerEvent(this.app.vault.on('create', onFsEvent));
  }

  onunload() { }

  async activate() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length) { this.app.workspace.revealLeaf(existing[0]); return; }
    const leaf = this.app.workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE, active: true });
  }

  async tabCounts() {
    const d = this.data;
    const [p, q, f, iv, s, ib] = await Promise.all([
      d.json('pipeline'), d.json('queue'), d.json('followups'), d.json('interviews'), d.json('scanfeed'), d.json('inbox'),
    ]);
    return {
      pipeline: p && p.rows ? p.rows.length : 0,
      queue: q && q.pendingCount != null ? q.pendingCount : 0,
      radar: f && f.metadata ? (f.metadata.actionable ?? 0) : 0,
      interviews: iv && iv.count != null ? iv.count : 0,
      scan: s && s.total != null ? s.total : 0,
      patterns: null,
      inbox: ib && ib.pendingCount != null ? ib.pendingCount : 0,
    };
  }

  runRefresh() {
    try {
      const { execFile } = require('child_process');
      const base = this.app.vault.adapter.basePath;
      new Notice('Hireloom Brain: refreshing…');
      execFile(process.execPath, [`${base}/second-brain/plugin/refresh.mjs`], { cwd: base, timeout: 60000 }, (err, stdout) => {
        if (err) new Notice(`Brain refresh failed: ${String(err.message).slice(0, 120)}`);
        else new Notice(String(stdout || 'Brain refresh OK').slice(0, 120));
      });
    } catch (e) {
      new Notice(`Brain refresh unavailable: ${String(e.message).slice(0, 120)}`);
    }
  }

  async selfTest() {
    const results = [];
    // 1. Build stamp matches the live code (this constant IS the live code).
    results.push(`stamp: ${BUILD_STAMP}`);
    // 2. Every tab renders real rows or its exact empty-state string.
    this.data.invalidate();
    for (const t of TABS) {
      const el = createDiv();
      try {
        await RENDERERS[t.id](el, this.data);
        const text = el.textContent || '';
        const isEmptyState = Object.values(EMPTY).some((s) => text.includes(s));
        const blank = text.trim().length === 0;
        results.push(`${t.id}: ${blank ? '❌ BLANK PANE' : isEmptyState ? '✓ empty-state' : `✓ real data (${text.length} chars)`}`);
      } catch (e) {
        results.push(`${t.id}: ❌ render threw: ${String(e.message).slice(0, 80)}`);
      }
    }
    const failed = results.filter((r) => r.includes('❌')).length;
    const summary = `Hireloom Brain self-test — ${failed === 0 ? 'PASS' : `${failed} FAILURES`}\n${results.join('\n')}`;
    console.log(summary);
    new Notice(summary.split('\n').slice(0, 4).join('\n'), 8000);
    // 3. The only user-layer write the plugin ever makes: a self-test line in BUILD-LOG.md.
    try {
      const line = `\n- self-test (${BUILD_STAMP}): ${failed === 0 ? 'PASS' : `${failed} failures`} — ${results.slice(1).join(' · ')}\n`;
      await this.app.vault.adapter.append('BUILD-LOG.md', line);
    } catch (e) { /* BUILD-LOG missing is fine */ }
  }
};

class BrainSettings extends PluginSettingTab {
  constructor(app, plugin) { super(app, plugin); this.plugin = plugin; }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl('h3', { text: 'Hireloom Second Brain' });
    new Setting(containerEl).setName('Build stamp').setDesc(BUILD_STAMP);
    new Setting(containerEl)
      .setName('Data source')
      .setDesc(`${API_DIR}/ — regenerated by second-brain/plugin/refresh.mjs (launchd every 30 min, or the ↻ button)`);
    new Setting(containerEl)
      .setName('Self-test')
      .setDesc('Verifies every tab renders real rows or its exact empty state — never a blank pane.')
      .addButton((b) => b.setButtonText('Run').onClick(() => this.plugin.selfTest()));
  }
}
