/* Hireloom Second Brain — Obsidian plugin (desktop).
 * Reads ONLY _brain_api/*.json (generated by second-brain/plugin/refresh.mjs
 * from Hireloom's real files). Never invents data: every tab renders real rows
 * or its exact empty-state string from the spec's binding table. Writes nothing
 * to user-layer files except an optional self-test line in BUILD-LOG.md.
 */
'use strict';

const { Plugin, ItemView, PluginSettingTab, Setting, Notice } = require('obsidian');

const BUILD_STAMP = 'hireloom-brain v0.1.0 · build 2026-06-11.4';
const VIEW_TYPE = 'hireloom-brain-view';
const API_DIR = '_brain_api';

// Canonical kanban order (templates/states.yml)
const STATE_ORDER = ['Evaluated', 'Applied', 'Responded', 'Interview', 'Offer', 'Rejected', 'Discarded', 'SKIP'];

// Exact empty states from the spec's tab-binding contract
const EMPTY = {
  pipeline: 'No applications tracked — paste a job URL or run /career-ops scan',
  queue: 'No ranked pool — run the batch pipeline or paste URLs into data/pipeline.md',
  radar: 'No applied roles awaiting response',
  interviews: 'Nothing in interview stage yet',
  scan: 'Scanner hasn’t run — node engine/scan/scan.mjs',
  patterns: 'Too few outcomes to analyze yet',
  inbox: 'Inbox empty',
};

const TABS = [
  { id: 'overview', label: 'Overview' },
  { id: 'pipeline', label: 'Pipeline' },
  { id: 'queue', label: 'Apply Queue' },
  { id: 'radar', label: 'Follow-up Radar' },
  { id: 'interviews', label: 'Interviews' },
  { id: 'scan', label: 'Scan Feed' },
  { id: 'patterns', label: 'Patterns' },
  { id: 'inbox', label: 'Inbox' },
];

class BrainData {
  constructor(app) {
    this.app = app;
    this.cache = new Map();
  }
  invalidate() { this.cache.clear(); }
  async json(name) {
    if (this.cache.has(name)) return this.cache.get(name);
    let value = null;
    try {
      const raw = await this.app.vault.adapter.read(`${API_DIR}/${name}.json`);
      value = JSON.parse(raw);
    } catch (e) {
      value = { missing: true, readError: String(e && e.message || e) };
    }
    this.cache.set(name, value);
    return value;
  }
}

function rowsOrEmpty(el, items, emptyText, renderRow) {
  if (!items || items.length === 0) {
    el.createDiv({ cls: 'hb-empty', text: emptyText });
    return false;
  }
  items.forEach(renderRow);
  return true;
}

const RENDERERS = {
  // Overview — the command-center landing: ask-bar + colored stat cards.
  // Every number binds to _brain_api; absent sources show honest empty text.
  async overview(el, data, plugin) {
    // Ask bar
    const ask = el.createDiv({ cls: 'hb-ask' });
    const input = ask.createEl('input', { attr: { placeholder: 'Ask your second brain…' } });
    const btn = ask.createEl('button', { cls: 'hb-ask-btn', text: 'Ask →' });
    const chips = el.createDiv({ cls: 'hb-ask-chips' });
    const answerHost = el.createDiv();
    const fire = () => { if (input.value.trim() && plugin) plugin.ask(input.value.trim(), answerHost, btn); };
    btn.onClickEvent(fire);
    input.addEventListener('keydown', (e) => { if (e.key === 'Enter') fire(); });
    ['Who is going cold?', "What's next in my queue?", 'How are my interviews looking?'].forEach((q) => {
      const c = chips.createEl('button', { cls: 'hb-ask-chip', text: q });
      c.onClickEvent(() => { input.value = q; fire(); });
    });

    const [p, f, q, s, iv, spend] = await Promise.all([
      data.json('pipeline'), data.json('followups'), data.json('queue'),
      data.json('scanfeed'), data.json('interviews'), data.json('spend'),
    ]);
    const grid = el.createDiv({ cls: 'hb-cards' });
    const card = (color, title) => {
      const c = grid.createDiv({ cls: `hb-ccard hb-cc-${color}` });
      const h = c.createDiv({ cls: 'hb-ccard-h' });
      h.createSpan({ cls: 'hb-cdot' });
      h.createSpan({ text: title });
      return c;
    };

    // 💸 Claude spend (API-equivalent, honestly labeled)
    const cs = card('violet', '💸 Claude spend');
    if (spend && spend.today) {
      cs.createDiv({ cls: 'hb-big', text: `$${spend.today.usd.toFixed(2)}` });
      cs.createDiv({ cls: 'hb-big-sub', text: 'today · API-equivalent value (subscription)' });
      const g = cs.createDiv({ cls: 'hb-statgrid' });
      [['7-day', `$${spend.last7d.usd.toFixed(2)}`], ['all-time', `$${spend.allTime.usd.toFixed(2)}`],
       ['sessions', String(spend.allTime.sessions)], ['messages', String(spend.allTime.messages)]]
        .forEach(([k, v]) => { g.createDiv({ cls: 'k', text: k }); g.createDiv({ cls: 'v', text: v }); });
      const days = spend.days || [];
      if (days.length > 1) {
        const max = Math.max(...days.map((d) => d.usd), 0.01);
        const mini = cs.createDiv({ cls: 'hb-mini' });
        days.forEach((d) => mini.createDiv({ attr: { style: `height:${Math.max(6, Math.round((d.usd / max) * 100))}%`, title: `${d.date}: $${d.usd}` } }));
      }
    } else {
      cs.createDiv({ cls: 'hb-empty', text: 'Spend card not generated — node second-brain/plugin/spend.mjs' });
    }

    // 🔥 Needs you now — overdue follow-ups
    const cn = card('orange', '🔥 Needs you now');
    const overdue = ((f && f.entries) || []).filter((e) => /overdue|urgent/i.test(e.urgency || ''))
      .sort((a, b) => (b.daysSinceApplication || 0) - (a.daysSinceApplication || 0));
    if (overdue.length === 0) cn.createDiv({ cls: 'hb-empty', text: EMPTY.radar });
    else {
      cn.createDiv({ cls: 'hb-big', text: String((f.metadata && f.metadata.overdue) || overdue.length) });
      cn.createDiv({ cls: 'hb-big-sub', text: 'follow-ups overdue' });
      overdue.slice(0, 5).forEach((e) => {
        const l = cn.createDiv({ cls: 'hb-line' });
        l.createSpan({ cls: 'hb-co', text: e.company });
        l.createSpan({ cls: 'hb-num', text: `${e.daysSinceApplication}d` });
      });
    }

    // 🎤 Interviews
    const ci = card('gold', '🎤 Interviews');
    const ivRows = (iv && iv.rows) || [];
    if (ivRows.length === 0) ci.createDiv({ cls: 'hb-empty', text: EMPTY.interviews });
    else {
      ci.createDiv({ cls: 'hb-big', text: String(ivRows.length) });
      ci.createDiv({ cls: 'hb-big-sub', text: 'in interview stage' });
      ivRows.forEach((r) => {
        const l = ci.createDiv({ cls: 'hb-line', attr: { title: r.notes || '' } });
        l.createSpan({ cls: 'hb-co', text: r.company });
        l.createSpan({ cls: 'hb-num', text: `${(r.prepFiles || []).length} prep files` });
      });
    }

    // 🗂 Apply queue
    const cq = card('teal', '🗂 Apply queue');
    if (!q || !q.head || q.head.length === 0) cq.createDiv({ cls: 'hb-empty', text: EMPTY.queue });
    else {
      cq.createDiv({ cls: 'hb-big', text: String(q.pendingCount) });
      cq.createDiv({ cls: 'hb-big-sub', text: `pending of ${q.total} ranked` });
      q.head.slice(0, 4).forEach((r) => {
        const l = cq.createDiv({ cls: 'hb-line' });
        l.createSpan({ cls: 'hb-num', text: `#${r.rank}` });
        l.createSpan({ cls: 'hb-co', text: r.company });
      });
    }

    // 📊 Pipeline
    const cp = card('green', '📊 Pipeline');
    const by = (p && p.byStatus) || {};
    const total = Object.values(by).reduce((a, b) => a + b, 0);
    if (!total) cp.createDiv({ cls: 'hb-empty', text: EMPTY.pipeline });
    else {
      cp.createDiv({ cls: 'hb-big', text: String(total) });
      cp.createDiv({ cls: 'hb-big-sub', text: 'applications tracked' });
      const bar = cp.createDiv({ cls: 'hb-stack' });
      STATE_ORDER.forEach((st, i) => {
        const v = by[st] || 0;
        if (v) bar.createDiv({ cls: `hb-seg hb-seg-${i % 5}`, attr: { style: `flex:${v}`, title: `${st}: ${v}` } });
      });
      const g = cp.createDiv({ cls: 'hb-statgrid' });
      STATE_ORDER.filter((st) => by[st]).forEach((st) => { g.createDiv({ cls: 'k', text: st }); g.createDiv({ cls: 'v', text: String(by[st]) }); });
    }

    // 📡 Scanner
    const cr = card('violet', '📡 Scanner');
    if (!s || !s.total) cr.createDiv({ cls: 'hb-empty', text: EMPTY.scan });
    else {
      cr.createDiv({ cls: 'hb-big', text: String(s.total) });
      cr.createDiv({ cls: 'hb-big-sub', text: `discoveries all-time · newest ${s.lastSeen}` });
      (s.recent || []).slice(0, 3).forEach((r) => {
        const l = cr.createDiv({ cls: 'hb-line' });
        l.createSpan({ cls: 'hb-co', text: r.company });
        l.createSpan({ cls: 'hb-num', text: r.first_seen });
      });
    }
  },

  async pipeline(el, data) {
    const p = await data.json('pipeline');
    const rows = (p && p.rows) || [];
    if (rows.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.pipeline }); return; }
    el.createDiv({ cls: 'hb-meta', text: `${rows.length} applications · source: data/applications.md` });
    const board = el.createDiv({ cls: 'hb-board' });
    for (const state of STATE_ORDER) {
      const inState = rows.filter((r) => r.status === state);
      if (inState.length === 0) continue;
      const col = board.createDiv({ cls: 'hb-col' });
      const h = col.createDiv({ cls: 'hb-col-h' });
      h.createSpan({ text: state });
      h.createSpan({ cls: 'hb-count', text: String(inState.length) });
      for (const r of inState.slice().sort((a, b) => (b.date || '').localeCompare(a.date || ''))) {
        const card = col.createDiv({ cls: 'hb-card', attr: { title: r.notes || '' } });
        card.createDiv({ cls: 'hb-co', text: r.company });
        card.createDiv({ cls: 'hb-role', text: r.role });
        const sub = card.createDiv({ cls: 'hb-sub' });
        sub.createSpan({ text: r.score || '' });
        sub.createSpan({ text: r.date || '' });
        sub.createSpan({ cls: 'hb-num', text: `#${r.num}` });
      }
    }
  },

  async queue(el, data) {
    const q = await data.json('queue');
    if (!q || q.missing || q.error || !q.head || q.head.length === 0) {
      el.createDiv({ cls: 'hb-empty', text: q && q.error ? `${EMPTY.queue} (${q.error})` : EMPTY.queue });
      return;
    }
    el.createDiv({ cls: 'hb-meta', text: `${q.pendingCount} pending of ${q.total} ranked · next rank ${q.nextRank} · source: output/pool-apply-order.json` });
    rowsOrEmpty(el, q.head, EMPTY.queue, (r) => {
      const row = el.createDiv({ cls: 'hb-row' });
      row.createSpan({ cls: 'hb-num', text: `#${r.rank}` });
      row.createSpan({ cls: 'hb-co', text: r.company });
      row.createSpan({ text: r.title });
      row.createSpan({ cls: 'hb-chip', text: r.ats || '' });
      if (r.url) row.createEl('a', { cls: 'hb-link', text: 'open', href: r.url });
    });
  },

  async radar(el, data) {
    const f = await data.json('followups');
    const entries = (f && f.entries) || [];
    const actionable = entries.filter((e) => e.urgency && e.urgency !== 'waiting');
    if (f && f.error) { el.createDiv({ cls: 'hb-empty', text: `${EMPTY.radar} (${f.error})` }); return; }
    if (actionable.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.radar }); return; }
    const m = f.metadata || {};
    el.createDiv({ cls: 'hb-meta', text: `${m.actionable ?? actionable.length} actionable · ${m.overdue ?? '–'} overdue · source: engine/tracker/followup-cadence.mjs` });
    actionable
      .slice()
      .sort((a, b) => (b.daysSinceApplication || 0) - (a.daysSinceApplication || 0))
      .slice(0, 40)
      .forEach((e) => {
        const row = el.createDiv({ cls: 'hb-row' });
        row.createSpan({ cls: `hb-chip${/overdue|urgent/i.test(e.urgency) ? ' hb-hot' : ''}`, text: e.urgency });
        row.createSpan({ cls: 'hb-co', text: e.company });
        row.createSpan({ text: e.role });
        row.createSpan({ cls: 'hb-num', text: `${e.daysSinceApplication}d since apply · follow-ups: ${e.followupCount}${e.nextFollowupDate ? ` · next ${e.nextFollowupDate}` : ''}` });
      });
  },

  async interviews(el, data) {
    const iv = await data.json('interviews');
    const rows = (iv && iv.rows) || [];
    if (rows.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.interviews }); return; }
    el.createDiv({ cls: 'hb-meta', text: `${rows.length} in interview stage · prep library: ${iv.prepDirCount} files in interview-prep/` });
    rows.forEach((r) => {
      const row = el.createDiv({ cls: 'hb-row', attr: { title: r.notes || '' } });
      row.createSpan({ cls: 'hb-co', text: r.company });
      row.createSpan({ text: r.role });
      const chips = row.createSpan();
      (r.prepFiles || []).slice(0, 5).forEach((p) => chips.createSpan({ cls: 'hb-chip', text: p }));
      if ((r.prepFiles || []).length === 0) chips.createSpan({ cls: 'hb-num', text: 'no prep files yet' });
    });
  },

  async scan(el, data) {
    const s = await data.json('scanfeed');
    if (!s || s.missing || !s.recent || s.recent.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.scan }); return; }
    el.createDiv({ cls: 'hb-meta', text: `${s.total} discoveries all-time · newest ${s.lastSeen} · source: data/scan-history.tsv` });
    s.recent.forEach((r) => {
      const row = el.createDiv({ cls: 'hb-row' });
      row.createSpan({ cls: 'hb-num', text: r.first_seen });
      row.createSpan({ cls: 'hb-co', text: r.company });
      row.createSpan({ text: r.title });
      row.createSpan({ cls: 'hb-chip', text: r.portal });
      if (r.url) row.createEl('a', { cls: 'hb-link', text: 'open', href: r.url });
    });
  },

  async patterns(el, data) {
    const p = await data.json('patterns');
    if (!p || p.error || !p.metadata || !p.metadata.total) { el.createDiv({ cls: 'hb-empty', text: EMPTY.patterns }); return; }
    const m = p.metadata;
    el.createDiv({ cls: 'hb-meta', text: `${m.total} analyzed (${m.dateRange.from} → ${m.dateRange.to}) · source: engine/tracker/analyze-patterns.mjs` });
    el.createDiv({ cls: 'hb-section-h', text: 'Outcomes' });
    const out = m.byOutcome || {};
    const total = Object.values(out).reduce((a, b) => a + b, 0) || 1;
    Object.entries(out).forEach(([k, v]) => {
      const row = el.createDiv({ cls: 'hb-row' });
      row.createSpan({ cls: 'hb-co', text: k });
      row.createSpan({ cls: 'hb-num', text: String(v) });
      row.createDiv({ cls: 'hb-bar', attr: { style: `width:${Math.max(2, Math.round((v / total) * 240))}px` } });
    });
    if (Array.isArray(p.recommendations) && p.recommendations.length) {
      el.createDiv({ cls: 'hb-section-h', text: 'Recommendations' });
      p.recommendations.slice(0, 8).forEach((r) => {
        el.createDiv({ cls: 'hb-row', text: typeof r === 'string' ? r : (r.text || r.message || JSON.stringify(r)) });
      });
    }
  },

  async inbox(el, data) {
    const i = await data.json('inbox');
    const pending = (i && i.pending) || [];
    if (pending.length === 0) { el.createDiv({ cls: 'hb-empty', text: EMPTY.inbox }); return; }
    el.createDiv({ cls: 'hb-meta', text: `${i.pendingCount} pending · source: data/pipeline.md` });
    pending.forEach((u) => {
      const row = el.createDiv({ cls: 'hb-row' });
      if (/^https?:/.test(u)) row.createEl('a', { cls: 'hb-link', text: u, href: u });
      else row.createSpan({ text: u });
    });
  },
};

class BrainView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.activeTab = 'overview';
  }
  getViewType() { return VIEW_TYPE; }
  getDisplayText() { return 'Hireloom Brain'; }
  getIcon() { return 'layout-dashboard'; }

  async onOpen() { await this.render(); }

  async render() {
    const root = this.contentEl;
    root.empty();
    root.addClass('hb-root');
    await this.renderHero(root);
    const tabs = root.createDiv({ cls: 'hb-tabs' });
    const counts = await this.plugin.tabCounts();
    for (const t of TABS) {
      const tab = tabs.createDiv({ cls: `hb-tab${t.id === this.activeTab ? ' is-active' : ''}` });
      tab.createSpan({ text: t.label });
      if (counts[t.id] != null) tab.createSpan({ cls: 'hb-count', text: String(counts[t.id]) });
      tab.onClickEvent(() => { this.activeTab = t.id; this.render(); });
    }
    const actions = tabs.createDiv({ cls: 'hb-actions' });
    const refreshBtn = actions.createEl('button', { cls: 'hb-btn', text: '↻ refresh data' });
    refreshBtn.onClickEvent(() => this.plugin.runRefresh());
    const body = root.createDiv();
    await RENDERERS[this.activeTab](body, this.plugin.data, this.plugin);
  }

  // Greeting + KPI stat cards — every number binds to _brain_api (no theater).
  async renderHero(root) {
    const d = this.plugin.data;
    const [meta, f, q, s] = await Promise.all([
      d.json('meta'), d.json('followups'), d.json('queue'), d.json('scanfeed'),
    ]);
    const hero = root.createDiv({ cls: 'hb-hero' });
    const h = new Date().getHours();
    const part = h < 5 ? '🦉 Up late' : h < 12 ? '🌅 Good morning' : h < 18 ? '🌤 Good afternoon' : '🌙 Good evening';
    const name = meta && meta.user && meta.user.firstName ? `, ${meta.user.firstName}` : '';
    const top = hero.createDiv({ cls: 'hb-hero-top' });
    top.createDiv({ cls: 'hb-greet', text: `${part}${name}` });
    // Freshness: green dot if the machine layer ran in the last 35 min.
    const right = top.createDiv({ cls: 'hb-hero-right' });
    try {
      const st = await this.app.vault.adapter.stat('_brain_api/meta.json');
      const ageMin = st ? (Date.now() - st.mtime) / 60000 : Infinity;
      right.createSpan({ cls: `hb-dot ${ageMin < 35 ? 'is-fresh' : 'is-stale'}` });
      right.createSpan({ text: st ? `Updated ${new Date(st.mtime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'never refreshed' });
    } catch (e) { /* stat unsupported — skip freshness */ }
    // Where things stand — one honest sentence from real counts.
    const counts0 = (meta && meta.counts) || {};
    const standBits = [];
    if (counts0.interviews) standBits.push(`${counts0.interviews} interview${counts0.interviews === 1 ? '' : 's'} live`);
    if (f && f.metadata && f.metadata.overdue) standBits.push(`${f.metadata.overdue} follow-ups overdue`);
    if (q && q.nextRank != null) standBits.push(`queue head #${q.nextRank}`);
    hero.createDiv({
      cls: 'hb-subline',
      text: `${new Date().toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric' })} · Where things stand: ${standBits.join(' · ') || 'all quiet'}`,
    });
    // Action pills — REAL actions only (no theater buttons).
    const pills = hero.createDiv({ cls: 'hb-pills' });
    const pill = (label, fn) => { const b = pills.createEl('button', { cls: 'hb-pill', text: label }); b.onClickEvent(fn); };
    pill('↻ Brain Refresh', () => this.plugin.runRefresh());
    pill('🧪 Self-Test', () => this.plugin.selfTest());
    pill('🌅 Morning Digest', () => this.app.workspace.openLinkText('_brain_api/digest.md', '/', true));
    const counts = (meta && meta.counts) || {};
    const by = counts.byStatus || {};
    const kpis = hero.createDiv({ cls: 'hb-kpis' });
    const kpi = (label, value, accent) => {
      const card = kpis.createDiv({ cls: `hb-kpi hb-acc-${accent}` });
      card.createDiv({ cls: 'hb-kpi-v', text: String(value ?? '–') });
      card.createDiv({ cls: 'hb-kpi-l', text: label });
    };
    kpi('tracked', counts.tracked, 'ox');
    kpi('applied', by.Applied || 0, 'ember');
    kpi('interviews', counts.interviews, 'gold');
    kpi('responded', by.Responded || 0, 'sage');
    kpi('overdue follow-ups', f && f.metadata ? f.metadata.overdue : '–', 'ox');
    kpi('queue pending', q && q.pendingCount != null ? q.pendingCount : '–', 'ember');
    kpi('scanned all-time', s && s.total != null ? s.total : '–', 'slate');
    // Stacked pipeline bar — proportional, real counts, canonical order.
    const total = Object.values(by).reduce((a, b) => a + b, 0);
    if (total > 0) {
      const bar = hero.createDiv({ cls: 'hb-stack' });
      STATE_ORDER.forEach((st, i) => {
        const v = by[st] || 0;
        if (!v) return;
        bar.createDiv({ cls: `hb-seg hb-seg-${i % 5}`, attr: { style: `flex:${v}`, title: `${st}: ${v}` } });
      });
    }
  }
}

module.exports = class HireloomBrain extends Plugin {
  async onload() {
    this.data = new BrainData(this.app);
    this.settings = Object.assign({ }, await this.loadData());

    this.registerView(VIEW_TYPE, (leaf) => new BrainView(leaf, this));
    this.addRibbonIcon('layout-dashboard', 'Hireloom Brain', () => this.activate());

    this.addCommand({ id: 'open', name: 'Open dashboard', callback: () => this.activate() });
    this.addCommand({ id: 'refresh', name: 'Refresh data now', callback: () => this.runRefresh() });
    this.addCommand({ id: 'self-test', name: 'Run self-test', callback: () => this.selfTest() });

    this.addSettingTab(new BrainSettings(this.app, this));

    // Debounced re-render when the machine layer (or tracker) changes.
    let timer = null;
    const onFsEvent = (file) => {
      const p = (file && file.path) || '';
      if (!p.startsWith(`${API_DIR}/`) && !p.startsWith('data/')) return;
      clearTimeout(timer);
      timer = setTimeout(() => {
        this.data.invalidate();
        this.app.workspace.getLeavesOfType(VIEW_TYPE).forEach((l) => l.view && l.view.render && l.view.render());
      }, 400);
    };
    this.registerEvent(this.app.vault.on('modify', onFsEvent));
    this.registerEvent(this.app.vault.on('create', onFsEvent));
  }

  onunload() { }

  async activate() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length) { this.app.workspace.revealLeaf(existing[0]); return; }
    const leaf = this.app.workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE, active: true });
  }

  async tabCounts() {
    const d = this.data;
    const [p, q, f, iv, s, ib] = await Promise.all([
      d.json('pipeline'), d.json('queue'), d.json('followups'), d.json('interviews'), d.json('scanfeed'), d.json('inbox'),
    ]);
    return {
      overview: null,
      pipeline: p && p.rows ? p.rows.length : 0,
      queue: q && q.pendingCount != null ? q.pendingCount : 0,
      radar: f && f.metadata ? (f.metadata.actionable ?? 0) : 0,
      interviews: iv && iv.count != null ? iv.count : 0,
      scan: s && s.total != null ? s.total : 0,
      patterns: null,
      inbox: ib && ib.pendingCount != null ? ib.pendingCount : 0,
    };
  }

  runRefresh() {
    try {
      // Inside Obsidian's renderer, process.execPath is Obsidian itself — NOT
      // node (user-test finding #7). Resolve node via a login shell so the
      // user's real PATH (homebrew/nvm/asdf) applies.
      const { execFile } = require('child_process');
      const base = this.app.vault.adapter.basePath;
      new Notice('Hireloom Brain: refreshing…');
      execFile('/bin/zsh', ['-lc', `node "${base}/second-brain/plugin/refresh.mjs"`], { cwd: base, timeout: 60000 }, (err, stdout, stderr) => {
        if (err) new Notice(`Brain refresh failed: ${String(stderr || err.message).slice(0, 140)}`);
        else new Notice(String(stdout || 'Brain refresh OK').slice(0, 140));
      });
    } catch (e) {
      new Notice(`Brain refresh unavailable: ${String(e.message).slice(0, 120)}`);
    }
  }

  // Ask-bar: question + compact real facts → the user's own Claude CLI.
  // Answers ONLY from vault facts; one `claude -p` call per ask (user-initiated).
  ask(question, hostEl, btn) {
    const { spawn } = require('child_process');
    const base = this.app.vault.adapter.basePath;
    hostEl.empty();
    const out = hostEl.createDiv({ cls: 'hb-ask-answer', text: '🧠 thinking…' });
    if (btn) btn.disabled = true;
    Promise.all([this.data.json('meta'), this.data.json('followups'), this.data.json('queue'), this.data.json('interviews')])
      .then(([meta, f, q, iv]) => {
        const facts = {
          counts: meta && meta.counts,
          overdueTop: ((f && f.entries) || []).filter((e) => /overdue|urgent/i.test(e.urgency || '')).slice(0, 10)
            .map((e) => ({ company: e.company, role: e.role, days: e.daysSinceApplication, followups: e.followupCount })),
          queueHead: ((q && q.head) || []).slice(0, 8).map((r) => ({ rank: r.rank, company: r.company, title: r.title })),
          interviews: ((iv && iv.rows) || []).map((r) => ({ company: r.company, role: r.role, notes: (r.notes || '').slice(0, 200) })),
        };
        const prompt = `You are the Hireloom Second Brain ask-bar. Answer ONLY from these job-search facts (JSON below). 2-4 sentences, direct, no preamble, no markdown headers. If the facts can't answer it, say so plainly.\n\nFACTS: ${JSON.stringify(facts)}\n\nQUESTION: ${question}`;
        const child = spawn('/bin/zsh', ['-lc', 'claude -p --max-turns 1 2>/dev/null'], { cwd: base, timeout: 120000 });
        let buf = '';
        child.stdout.on('data', (c) => { buf += c; });
        child.on('close', (code) => {
          out.setText(buf.trim() || `ask failed (exit ${code}) — is the claude CLI on your PATH?`);
          if (btn) btn.disabled = false;
        });
        child.on('error', (e) => { out.setText(`ask unavailable: ${e.message}`); if (btn) btn.disabled = false; });
        child.stdin.write(prompt);
        child.stdin.end();
      });
  }

  async selfTest() {
    const results = [];
    // 1. Build stamp matches the live code (this constant IS the live code).
    results.push(`stamp: ${BUILD_STAMP}`);
    // 2. Every tab renders real rows or its exact empty-state string.
    this.data.invalidate();
    for (const t of TABS) {
      const el = createDiv();
      try {
        await RENDERERS[t.id](el, this.data);
        const text = el.textContent || '';
        const isEmptyState = Object.values(EMPTY).some((s) => text.includes(s));
        const blank = text.trim().length === 0;
        results.push(`${t.id}: ${blank ? '❌ BLANK PANE' : isEmptyState ? '✓ empty-state' : `✓ real data (${text.length} chars)`}`);
      } catch (e) {
        results.push(`${t.id}: ❌ render threw: ${String(e.message).slice(0, 80)}`);
      }
    }
    const failed = results.filter((r) => r.includes('❌')).length;
    const summary = `Hireloom Brain self-test — ${failed === 0 ? 'PASS' : `${failed} FAILURES`}\n${results.join('\n')}`;
    console.log(summary);
    new Notice(summary.split('\n').slice(0, 4).join('\n'), 8000);
    // 3. The only user-layer write the plugin ever makes: a self-test line in BUILD-LOG.md.
    try {
      const line = `\n- self-test (${BUILD_STAMP}): ${failed === 0 ? 'PASS' : `${failed} failures`} — ${results.slice(1).join(' · ')}\n`;
      await this.app.vault.adapter.append('BUILD-LOG.md', line);
    } catch (e) { /* BUILD-LOG missing is fine */ }
  }
};

class BrainSettings extends PluginSettingTab {
  constructor(app, plugin) { super(app, plugin); this.plugin = plugin; }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl('h3', { text: 'Hireloom Second Brain' });
    new Setting(containerEl).setName('Build stamp').setDesc(BUILD_STAMP);
    new Setting(containerEl)
      .setName('Data source')
      .setDesc(`${API_DIR}/ — regenerated by second-brain/plugin/refresh.mjs (launchd every 30 min, or the ↻ button)`);
    new Setting(containerEl)
      .setName('Self-test')
      .setDesc('Verifies every tab renders real rows or its exact empty state — never a blank pane.')
      .addButton((b) => b.setButtonText('Run').onClick(() => this.plugin.selfTest()));
  }
}
