/**
 * tests/profile-edit.test.mjs — the non-destructive profile.yml patcher.
 *
 * The headline guarantee: editing a managed field must leave every UNmanaged
 * block (languages, eeo_voluntary, application_answers, education, resume_facts,
 * cv identity) and every comment byte-for-byte intact. The fixture mirrors the
 * real config/profile.yml shape so a regression that re-introduces the lossy
 * full-rewrite path fails here.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  readProfileFields, applyProfileEdits, validateProfileEdits, MANAGED,
  FREE_TEXT_KEY, CUSTOM_ANSWERS_KEY,
} from '../apps/web/lib/profile-edit.mjs';

const FIXTURE = `# Career-Ops Profile Configuration
# Generated by the onboarding wizard. Edit any field directly.

candidate:
  full_name: "Ramy Sherif"
  email: "ramy.sherif.work@gmail.com"
  phone: "416-275-4988"
  location: "Toronto, ON, Canada"
  linkedin: "www.linkedin.com/in/ramy-sherif/"
  portfolio_url: ""
  github: ""
  twitter: ""

target_roles:
  primary:
    - "Project Manager"
    - "Senior Project Manager"
    - "Program Manager"
  archetypes: []

narrative:
  headline: "Program / Project Manager"
  exit_story: "Pivoting from physical-ops PM into tech/delivery PM."
  superpowers:
    - "Strong Leader"
    - "Generate Strong Results"
  best_achievement: "Situation.\\nAction.\\nResult: $1.4M cost-out."
  proof_points: []

compensation:
  target_range: "$100,000"
  currency: "CAD"
  minimum: "$65,000"
  location_flexibility: "Canada-wide, open to relocation."

location:
  city: "Toronto"
  country: "Canada"
  timezone: ""
  visa_status: ""

work_authorization:
  legally_authorized_to_work: "Yes"
  require_sponsorship: "No"
  work_permit_type: "Canadian Citizen"

languages:
  fluent: ["English"]
  none: ["French"]
  # HARD GATE: Ramy does NOT speak French.

eeo_voluntary:
  gender: "Male"
  # Prefer "Middle Eastern" when offered.
  race_ethnicity: "Middle Eastern"
  race_ethnicity_fallback: "Two or more races"
  hispanic_latino: "No"
  veteran_status: "I am not a protected veteran"
  disability_status: "No, I do not have a disability"
  sexual_orientation: "Heterosexual / Straight"
  transgender: "No"
  pronouns: "He/Him"

application_answers:
  over_18: "Yes"
  notice_period: "2 weeks"
  current_company: "Amazon"
  drivers_license: "Yes"

education:
  school: "University of Toronto"
  degree: "Bachelor of Science"
  discipline: "Astrophysics & Physics"

resume_facts:
  preserved_companies:
  preserved_school: ""

# CV rendering identity (read by lib/identity.mjs).
cv:
  contact_location: "Ajax, ON (open to relocation)"
  contact_linkedin: "linkedin.com/in/ramy-sherif"
  education:
    - degree: "BSc, Astrophysics & Physics"
      org: "University of Toronto"
      date: "2018 – 2022"
  experience_order:
    - "amazon"
    - "wyr"
`;

// Pull a top-level block's text (key line through just before the next
// top-level key) so we can assert it's untouched.
function blockText(text, key) {
  const lines = text.split('\n');
  let start = lines.findIndex(l => new RegExp('^' + key + ':').test(l));
  if (start === -1) return null;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (/^[A-Za-z_][\w-]*:/.test(lines[i])) { end = i; break; }
  }
  return lines.slice(start, end).join('\n');
}

test('readProfileFields extracts the managed surface', () => {
  const f = readProfileFields(FIXTURE);
  assert.equal(f.candidate.full_name, 'Ramy Sherif');
  assert.equal(f.candidate.email, 'ramy.sherif.work@gmail.com');
  assert.equal(f.candidate.linkedin, 'www.linkedin.com/in/ramy-sherif/');
  assert.deepEqual(f.target_roles.primary, ['Project Manager', 'Senior Project Manager', 'Program Manager']);
  assert.equal(f.narrative.headline, 'Program / Project Manager');
  assert.deepEqual(f.narrative.superpowers, ['Strong Leader', 'Generate Strong Results']);
  assert.equal(f.narrative.best_achievement, 'Situation.\nAction.\nResult: $1.4M cost-out.'); // \n unescaped
  assert.equal(f.compensation.currency, 'CAD');
  assert.equal(f.work_authorization.work_permit_type, 'Canadian Citizen');
});

test('editing managed fields leaves every UNMANAGED block byte-identical', () => {
  const edited = applyProfileEdits(FIXTURE, {
    candidate: { full_name: 'Ramy A. Sherif', phone: '647-000-0000' },
    compensation: { target_range: '$120,000', minimum: '$80,000' },
    target_roles: { primary: ['Delivery Manager', 'Technical Program Manager'] },
    narrative: { superpowers: ['Calm under pressure', 'Ships on time', 'Builds trust'] },
  });
  for (const key of ['languages', 'eeo_voluntary', 'application_answers', 'education', 'resume_facts', 'cv', 'location']) {
    assert.equal(blockText(edited, key), blockText(FIXTURE, key), `${key} block must be untouched`);
  }
  // comments preserved
  assert.ok(edited.includes('# HARD GATE: Ramy does NOT speak French.'));
  assert.ok(edited.includes('# Prefer "Middle Eastern" when offered.'));
  assert.ok(edited.includes('# CV rendering identity (read by lib/identity.mjs).'));
});

test('editing changes ONLY the targeted fields', () => {
  const edited = applyProfileEdits(FIXTURE, {
    candidate: { full_name: 'Ramy A. Sherif' },
    compensation: { target_range: '$120,000' },
  });
  const f = readProfileFields(edited);
  assert.equal(f.candidate.full_name, 'Ramy A. Sherif');
  assert.equal(f.compensation.target_range, '$120,000');
  // untouched managed siblings keep their values
  assert.equal(f.candidate.email, 'ramy.sherif.work@gmail.com');
  assert.equal(f.compensation.currency, 'CAD');
  // unmanaged candidate fields survive
  assert.ok(edited.includes('portfolio_url: ""'));
});

test('full round-trip with no changes is a near-noop (unmanaged blocks identical)', () => {
  const same = applyProfileEdits(FIXTURE, readProfileFields(FIXTURE));
  for (const key of ['languages', 'eeo_voluntary', 'application_answers', 'education', 'resume_facts', 'cv', 'location']) {
    assert.equal(blockText(same, key), blockText(FIXTURE, key));
  }
  // managed scalars re-quote identically
  assert.equal(readProfileFields(same).candidate.full_name, 'Ramy Sherif');
  assert.deepEqual(readProfileFields(same).target_roles.primary, readProfileFields(FIXTURE).target_roles.primary);
});

test('list edit: replacing target roles updates items, keeps sibling key', () => {
  const edited = applyProfileEdits(FIXTURE, { target_roles: { primary: ['Only One Role'] } });
  assert.deepEqual(readProfileFields(edited).target_roles.primary, ['Only One Role']);
  assert.ok(edited.includes('archetypes: []'), 'the sibling archetypes key must survive');
});

test('empty list collapses to []', () => {
  const edited = applyProfileEdits(FIXTURE, { narrative: { superpowers: [] } });
  assert.match(blockText(edited, 'narrative'), /superpowers: \[\]/);
  assert.deepEqual(readProfileFields(edited).narrative.superpowers, []);
});

test('best_achievement with newlines round-trips through quoting', () => {
  const edited = applyProfileEdits(FIXTURE, { narrative: { best_achievement: 'Line one\nLine two' } });
  assert.equal(readProfileFields(edited).narrative.best_achievement, 'Line one\nLine two');
  assert.ok(edited.includes('best_achievement: "Line one\\nLine two"')); // escaped on disk
});

test('validateProfileEdits flags bad email and empty roles', () => {
  assert.deepEqual(validateProfileEdits({ candidate: { full_name: 'X' } }), []);
  assert.ok(validateProfileEdits({ candidate: { email: 'not-an-email' } }).length);
  assert.ok(validateProfileEdits({ target_roles: { primary: ['', '  '] } }).length);
  assert.ok(validateProfileEdits({ narrative: { superpowers: 'not-array' } }).length);
});

test('editing eeo_voluntary in place preserves its comment + sibling fields', () => {
  // eeo_voluntary IS managed now (surgically) — editing one field must keep the
  // MENA comment and the extra fields the wizard serializer never knew about.
  const edited = applyProfileEdits(FIXTURE, { eeo_voluntary: { gender: 'Prefer not to say' } });
  const f = readProfileFields(edited);
  assert.equal(f.eeo_voluntary.gender, 'Prefer not to say');
  assert.equal(f.eeo_voluntary.race_ethnicity, 'Middle Eastern', 'sibling field untouched');
  assert.equal(f.eeo_voluntary.race_ethnicity_fallback, 'Two or more races', 'extra field survives');
  assert.ok(edited.includes('# Prefer "Middle Eastern" when offered.'), 'comment survives');
});

test('education + resume_facts stay UNMANAGED (we never edit them)', () => {
  for (const forbidden of ['education', 'resume_facts']) {
    assert.ok(!(forbidden in MANAGED), `${forbidden} must stay unmanaged`);
  }
});

test('application_answers + languages are editable in place', () => {
  const edited = applyProfileEdits(FIXTURE, {
    application_answers: { notice_period: '1 month', drivers_license: 'No' },
    languages: { fluent: ['English', 'Spanish'] },
  });
  const f = readProfileFields(edited);
  assert.equal(f.application_answers.notice_period, '1 month');
  assert.equal(f.application_answers.drivers_license, 'No');
  assert.equal(f.application_answers.current_company, 'Amazon', 'untouched sibling');
  assert.deepEqual(f.languages.fluent, ['English', 'Spanish']);
  assert.deepEqual(f.languages.none, ['French'], 'none list untouched');
});

test('free-text additional_context: add, read, edit, remove round-trip', () => {
  // add
  let t = applyProfileEdits(FIXTURE, { [FREE_TEXT_KEY]: 'Open to contract work.\nPrefers async teams.' });
  assert.equal(readProfileFields(t)[FREE_TEXT_KEY], 'Open to contract work.\nPrefers async teams.');
  assert.match(t, /additional_context: \|/);
  // arbitrary text that LOOKS like yaml stays inert inside the block
  t = applyProfileEdits(FIXTURE, { [FREE_TEXT_KEY]: 'gender: actually a trap\nnested: value' });
  assert.equal(readProfileFields(t)[FREE_TEXT_KEY], 'gender: actually a trap\nnested: value');
  assert.equal(readProfileFields(t).eeo_voluntary.gender, 'Male', 'real gender field NOT clobbered by free-text');
  // edit
  t = applyProfileEdits(t, { [FREE_TEXT_KEY]: 'changed' });
  assert.equal(readProfileFields(t)[FREE_TEXT_KEY], 'changed');
  // remove
  t = applyProfileEdits(t, { [FREE_TEXT_KEY]: '' });
  assert.equal(readProfileFields(t)[FREE_TEXT_KEY], '');
  assert.ok(!/additional_context:/.test(t), 'empty value removes the key');
});

test('custom_answers object list round-trips and dedups blanks', () => {
  const t = applyProfileEdits(FIXTURE, { [CUSTOM_ANSWERS_KEY]: [
    { question: 'Why this company?', answer: 'Mission fit.' },
    { question: '', answer: '' },                                  // dropped
    { question: 'Salary in EUR?', answer: '€90k' },
  ] });
  const ca = readProfileFields(t)[CUSTOM_ANSWERS_KEY];
  assert.equal(ca.length, 2);
  assert.deepEqual(ca[0], { question: 'Why this company?', answer: 'Mission fit.' });
  assert.deepEqual(ca[1], { question: 'Salary in EUR?', answer: '€90k' });
});

test('adding free-text + custom answers leaves the original blocks intact', () => {
  const edited = applyProfileEdits(FIXTURE, {
    [FREE_TEXT_KEY]: 'note',
    [CUSTOM_ANSWERS_KEY]: [{ question: 'q', answer: 'a' }],
  });
  for (const key of ['candidate', 'languages', 'eeo_voluntary', 'application_answers', 'education', 'cv']) {
    assert.equal(blockText(edited, key), blockText(FIXTURE, key), `${key} untouched when appending new keys`);
  }
});

test('editing a field preserves its trailing inline comment', () => {
  const yml = [
    'application_answers:',
    '  drivers_license: "Yes"                # valid Ontario license',
    '  citizenship: "Canadian citizen"       # for citizenship questions',
    '',
  ].join('\n');
  const edited = applyProfileEdits(yml, { application_answers: { drivers_license: 'No' } });
  assert.match(edited, /drivers_license: "No"\s+# valid Ontario license/);
  assert.match(edited, /citizenship: "Canadian citizen"\s+# for citizenship questions/, 'sibling comment intact');
});

test('a value containing # is not mistaken for a comment', () => {
  const yml = 'application_answers:\n  current_company: "C# Shop"\n';
  const edited = applyProfileEdits(yml, { application_answers: { current_company: 'F# Inc' } });
  assert.match(edited, /current_company: "F# Inc"\s*$/m);
  assert.equal(readProfileFields(edited).application_answers.current_company, 'F# Inc');
});

test('editing a scalar preserves its trailing inline comment', () => {
  const yml = [
    'application_answers:',
    '  drivers_license: "Yes"      # "Valid driver\'s license?": Yes (Ontario)',
    '  citizenship: "Canadian citizen"',
  ].join('\n');
  const edited = applyProfileEdits(yml, { application_answers: { drivers_license: 'No' } });
  assert.match(edited, /drivers_license: "No"\s+# "Valid driver's license\?": Yes \(Ontario\)/,
    'value changes, inline comment stays');
  assert.match(edited, /citizenship: "Canadian citizen"/, 'sibling untouched');
});

test('validateProfileEdits bounds the new free-text + custom_answers', () => {
  assert.deepEqual(validateProfileEdits({ [FREE_TEXT_KEY]: 'fine' }), []);
  assert.ok(validateProfileEdits({ [FREE_TEXT_KEY]: 'x'.repeat(20001) }).length);
  assert.ok(validateProfileEdits({ [CUSTOM_ANSWERS_KEY]: 'not-array' }).length);
  assert.ok(validateProfileEdits({ [CUSTOM_ANSWERS_KEY]: [{ question: 'x'.repeat(600), answer: 'y' }] }).length);
});
