/**
 * dashboard-web/lib/onboard.mjs — Pure helpers for the onboarding wizard.
 *
 * No I/O, no module-level state. Exported so tests can import them directly
 * without booting the HTTP server. Mirror imports live in server.mjs.
 */

// ── YAML serialization ──────────────────────────────────────────────────────
// Hand-rolled emitter for the `config/profile.yml` schema. Avoids a runtime
// dep on js-yaml since our schema is well-known and flat.

export function yamlQuote(s) {
  const str = s == null ? '' : String(s);
  return '"' + str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
    + '"';
}

export function serializeProfileYaml(p) {
  const b = (p && p.basics) || {};
  const c = (p && p.compensation) || {};
  const n = (p && p.narrative) || {};
  const wa = (p && p.work_authorization) || {};
  const eeo = (p && p.eeo_voluntary) || {};
  const rf = (p && p.resume_facts) || {};
  const linkedin = (b.linkedin || '').trim().replace(/^https?:\/\//i, '');
  const locParts = (b.location || '').split(',').map(s => s.trim()).filter(Boolean);

  const out = [];
  out.push('# Career-Ops Profile Configuration');
  out.push('# Generated by the onboarding wizard. Edit any field directly — the');
  out.push('# system picks up your changes on the next run.');
  out.push('');
  out.push('candidate:');
  out.push(`  full_name: ${yamlQuote(b.full_name)}`);
  out.push(`  email: ${yamlQuote(b.email)}`);
  out.push(`  phone: ${yamlQuote(b.phone || '')}`);
  out.push(`  location: ${yamlQuote(b.location || '')}`);
  out.push(`  linkedin: ${yamlQuote(linkedin)}`);
  out.push('  portfolio_url: ""');
  out.push('  github: ""');
  out.push('  twitter: ""');
  out.push('');
  out.push('target_roles:');
  out.push('  primary:');
  for (const r of (p && p.target_roles) || []) out.push(`    - ${yamlQuote(r)}`);
  out.push('  archetypes: []');
  out.push('');
  out.push('narrative:');
  out.push(`  headline: ${yamlQuote(b.headline || '')}`);
  out.push('  exit_story: ""');
  if (Array.isArray(n.superpowers) && n.superpowers.length) {
    out.push('  superpowers:');
    for (const sp of n.superpowers) out.push(`    - ${yamlQuote(sp)}`);
  } else {
    out.push('  superpowers: []');
  }
  if (n.best_achievement) {
    out.push(`  best_achievement: ${yamlQuote(n.best_achievement)}`);
  }
  if (Array.isArray(n.proof_points) && n.proof_points.some(pp => pp.name || pp.url)) {
    out.push('  proof_points:');
    for (const pp of n.proof_points) {
      if (!pp.name && !pp.url) continue;
      out.push(`    - name: ${yamlQuote(pp.name || '')}`);
      out.push(`      url: ${yamlQuote(pp.url || '')}`);
      out.push(`      hero_metric: ${yamlQuote(pp.hero_metric || '')}`);
    }
  } else {
    out.push('  proof_points: []');
  }
  out.push('');
  out.push('compensation:');
  out.push(`  target_range: ${yamlQuote(c.target_range || '')}`);
  out.push(`  currency: ${yamlQuote(c.currency || 'USD')}`);
  out.push(`  minimum: ${yamlQuote(c.minimum || '')}`);
  out.push(`  location_flexibility: ${yamlQuote(c.location_flexibility || '')}`);
  out.push('');
  if (Array.isArray(p && p.deal_breakers) && p.deal_breakers.length) {
    out.push('deal_breakers:');
    for (const d of p.deal_breakers) out.push(`  - ${yamlQuote(d)}`);
    out.push('');
  }
  out.push('location:');
  out.push(`  city: ${yamlQuote(locParts[0] || '')}`);
  out.push(`  country: ${yamlQuote(locParts[locParts.length - 1] || '')}`);
  out.push('  timezone: ""');
  out.push('  visa_status: ""');
  out.push('');

  // Work authorization (auto-fill for "Are you legally authorized?" / "Do you
  // require sponsorship?" — the two questions every US/CA application asks).
  // Pattern adopted from ApplyPilot.
  out.push('work_authorization:');
  out.push(`  legally_authorized_to_work: ${yamlQuote(wa.legally_authorized_to_work || '')}`);
  out.push(`  require_sponsorship: ${yamlQuote(wa.require_sponsorship || '')}`);
  out.push(`  work_permit_type: ${yamlQuote(wa.work_permit_type || '')}`);
  out.push('');

  // EEO voluntary self-id defaults — most US Fortune 500 EEO sections are
  // optional but mandatory to render. "Decline to self-identify" is always a
  // valid answer; users can edit profile.yml to change.
  out.push('eeo_voluntary:');
  out.push(`  gender: ${yamlQuote(eeo.gender || 'Decline to self-identify')}`);
  out.push(`  race_ethnicity: ${yamlQuote(eeo.race_ethnicity || 'Decline to self-identify')}`);
  out.push(`  veteran_status: ${yamlQuote(eeo.veteran_status || 'I am not a protected veteran')}`);
  out.push(`  disability_status: ${yamlQuote(eeo.disability_status || 'I do not wish to answer')}`);
  out.push('');

  // Resume facts — the immutable identity guard. These are facts the AI
  // tailoring/cover-letter modes MUST treat as ground truth. Anything not
  // here cannot be claimed without explicit user consent. Prevents
  // hallucinated companies, projects, schools, and metrics.
  out.push('resume_facts:');
  out.push('  preserved_companies:');
  for (const x of (Array.isArray(rf.preserved_companies) ? rf.preserved_companies : [])) {
    if (x) out.push(`    - ${yamlQuote(x)}`);
  }
  out.push('  preserved_projects:');
  for (const x of (Array.isArray(rf.preserved_projects) ? rf.preserved_projects : [])) {
    if (x) out.push(`    - ${yamlQuote(x)}`);
  }
  out.push(`  preserved_school: ${yamlQuote(rf.preserved_school || '')}`);
  out.push('  real_metrics:');
  for (const x of (Array.isArray(rf.real_metrics) ? rf.real_metrics : [])) {
    if (x) out.push(`    - ${yamlQuote(x)}`);
  }
  out.push('');

  // CV rendering identity (read by lib/identity.mjs → all CV/cover renderers).
  // Education + certifications are rendered on every generated CV; without
  // them a new user's first render ships an empty Education section.
  const cv = (p && p.cv) || {};
  const edu = (Array.isArray(cv.education) ? cv.education : []).filter(e => e && (e.degree || e.org));
  const certs = (Array.isArray(cv.certifications) ? cv.certifications : []).filter(c => c && c.title);
  out.push('# CV rendering identity (lib/identity.mjs): the education and certification');
  out.push('# blocks printed on every generated resume. Optional display overrides:');
  out.push('# contact_location / contact_linkedin / experience_order — see');
  out.push('# config/profile.example.yml for the full reference.');
  out.push('cv:');
  if (edu.length) {
    out.push('  education:');
    for (const e of edu) {
      out.push(`    - degree: ${yamlQuote(e.degree || '')}`);
      out.push(`      org: ${yamlQuote(e.org || '')}`);
      out.push(`      date: ${yamlQuote(e.date || '')}`);
    }
  } else {
    out.push('  education: []');
  }
  if (certs.length) {
    out.push('  certifications:');
    for (const c of certs) {
      out.push(`    - title: ${yamlQuote(c.title || '')}`);
      out.push(`      org: ${yamlQuote(c.org || '')}`);
    }
  } else {
    out.push('  certifications: []');
  }
  out.push('');
  return out.join('\n');
}

// ── Validation ──────────────────────────────────────────────────────────────

export function validateOnboardPayload(p) {
  const errors = [];
  if (!p || typeof p !== 'object') { errors.push('payload required'); return errors; }
  const b = p.basics;
  if (!b || typeof b !== 'object') { errors.push('basics required'); return errors; }
  if (!b.full_name || typeof b.full_name !== 'string' || b.full_name.length < 2 || b.full_name.length > 100) errors.push('full_name invalid');
  if (!b.email || typeof b.email !== 'string' || !/.+@.+\..+/.test(b.email) || b.email.length > 200) errors.push('email invalid');
  for (const k of ['phone','location','linkedin','headline']) {
    if (b[k] != null && (typeof b[k] !== 'string' || b[k].length > 300)) errors.push(`${k} too long`);
  }
  if (!Array.isArray(p.target_roles) || p.target_roles.length === 0) errors.push('pick at least one target role');
  else if (p.target_roles.length > 50) errors.push('too many target_roles');
  for (const r of (p.target_roles || [])) {
    if (typeof r !== 'string' || r.length === 0 || r.length > 120) { errors.push('invalid role entry'); break; }
  }
  if (p.compensation && typeof p.compensation === 'object') {
    for (const k of ['target_range','minimum','currency','location_flexibility']) {
      if (p.compensation[k] != null && (typeof p.compensation[k] !== 'string' || p.compensation[k].length > 100)) errors.push(`compensation.${k} invalid`);
    }
  }
  if (p.deal_breakers != null) {
    if (!Array.isArray(p.deal_breakers)) errors.push('deal_breakers must be array');
    else if (p.deal_breakers.length > 50) errors.push('too many deal_breakers');
  }
  if (p.narrative && typeof p.narrative === 'object') {
    const n = p.narrative;
    if (n.superpowers != null && !Array.isArray(n.superpowers)) errors.push('superpowers must be array');
    else if (Array.isArray(n.superpowers) && n.superpowers.length > 10) errors.push('too many superpowers');
    if (n.best_achievement != null && (typeof n.best_achievement !== 'string' || n.best_achievement.length > 4000)) errors.push('best_achievement too long');
    if (n.proof_points != null && !Array.isArray(n.proof_points)) errors.push('proof_points must be array');
    else if (Array.isArray(n.proof_points) && n.proof_points.length > 20) errors.push('too many proof_points');
  }
  // Optional ApplyPilot-style sections — all string-bounded, all skip-friendly.
  if (p.work_authorization != null && typeof p.work_authorization === 'object') {
    for (const k of ['legally_authorized_to_work', 'require_sponsorship', 'work_permit_type']) {
      if (p.work_authorization[k] != null && (typeof p.work_authorization[k] !== 'string' || p.work_authorization[k].length > 200)) {
        errors.push(`work_authorization.${k} invalid`);
      }
    }
  }
  if (p.eeo_voluntary != null && typeof p.eeo_voluntary === 'object') {
    for (const k of ['gender', 'race_ethnicity', 'veteran_status', 'disability_status']) {
      if (p.eeo_voluntary[k] != null && (typeof p.eeo_voluntary[k] !== 'string' || p.eeo_voluntary[k].length > 200)) {
        errors.push(`eeo_voluntary.${k} invalid`);
      }
    }
  }
  if (p.resume_facts != null && typeof p.resume_facts === 'object') {
    const rf = p.resume_facts;
    for (const k of ['preserved_companies', 'preserved_projects', 'real_metrics']) {
      if (rf[k] != null && !Array.isArray(rf[k])) errors.push(`resume_facts.${k} must be array`);
      else if (Array.isArray(rf[k]) && rf[k].length > 100) errors.push(`resume_facts.${k} too many entries`);
      else if (Array.isArray(rf[k])) {
        for (const v of rf[k]) {
          if (typeof v !== 'string' || v.length > 300) { errors.push(`resume_facts.${k} entry invalid`); break; }
        }
      }
    }
    if (rf.preserved_school != null && (typeof rf.preserved_school !== 'string' || rf.preserved_school.length > 200)) {
      errors.push('resume_facts.preserved_school invalid');
    }
  }
  if (p.cv != null && typeof p.cv === 'object') {
    const cv = p.cv;
    if (cv.education != null && !Array.isArray(cv.education)) errors.push('cv.education must be array');
    else if (Array.isArray(cv.education)) {
      if (cv.education.length > 10) errors.push('cv.education too many entries');
      for (const e of cv.education) {
        for (const k of ['degree', 'org', 'date']) {
          if (e && e[k] != null && (typeof e[k] !== 'string' || e[k].length > 300)) { errors.push(`cv.education.${k} invalid`); break; }
        }
      }
    }
    if (cv.certifications != null && !Array.isArray(cv.certifications)) errors.push('cv.certifications must be array');
    else if (Array.isArray(cv.certifications)) {
      if (cv.certifications.length > 20) errors.push('cv.certifications too many entries');
      for (const c of cv.certifications) {
        for (const k of ['title', 'org']) {
          if (c && c[k] != null && (typeof c[k] !== 'string' || c[k].length > 300)) { errors.push(`cv.certifications.${k} invalid`); break; }
        }
      }
    }
  }
  return errors;
}

// ── Resume text extraction ──────────────────────────────────────────────────
// Pulled out of /api/onboard so we can unit-test the heuristics without HTTP.

export function extractProfileFromResume(text) {
  const out = { full_name: '', email: '', phone: '', linkedin: '', location: '', headline: '', education: [], certifications: [] };
  if (!text || typeof text !== 'string') return out;

  const emailMatch = text.match(/[\w.+-]+@[\w-]+\.[\w.-]+/);
  const phoneMatch = text.match(/(?:\+?\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}/);
  const linkedinMatch = text.match(/linkedin\.com\/in\/[\w-]+/i);
  out.email    = emailMatch ? emailMatch[0] : '';
  out.phone    = phoneMatch ? phoneMatch[0] : '';
  out.linkedin = linkedinMatch ? linkedinMatch[0] : '';

  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);

  for (const line of lines.slice(0, 5)) {
    const clean = line.replace(/^#+\s*/, '').replace(/\*+/g, '').trim();
    if (clean.length > 2 && clean.length < 60 && /^[A-Z]/.test(clean)
        && !clean.includes('@') && !clean.includes('http') && /\s/.test(clean)) {
      out.full_name = clean; break;
    }
  }

  // Headline: must be a SHORT title-line, not a full sentence about experience.
  // A good headline is ≤ 80 chars, doesn't end in a period, and reads like a
  // role descriptor ("Strategic Operator · AI Architect") rather than a CV bullet.
  const headlineKw = /director|head|manager|engineer|architect|lead|chief|vp|president|consultant|strategist|operator|founder|principal|staff|senior/i;
  for (const line of lines.slice(0, 10)) {
    const clean = line.replace(/^#+\s*/, '').replace(/\*+/g, '').trim();
    if (clean === out.full_name) continue;
    if (clean.length > 80) continue;          // too long — probably a CV bullet
    if (/[.!?]$/.test(clean)) continue;        // ends in sentence punctuation
    if (clean.includes('@') || /https?:\/\//i.test(clean)) continue;
    if (!headlineKw.test(clean)) continue;
    out.headline = clean; break;
  }

  // Location: try to pull "City, ST" or "City, Country" from the first 8 lines.
  // Resume contact lines often interleave fields with pipes/middots — split on those.
  for (const line of lines.slice(0, 8)) {
    const segments = line.split(/[|·•]/).map(s => s.trim()).filter(Boolean);
    for (const seg of segments) {
      if (seg.includes('@') || /\d{3}/.test(seg) || /https?:\/\//i.test(seg) || /linkedin/i.test(seg)) continue;
      const m = seg.match(/^([A-Z][A-Za-z .'-]{1,30}),\s*([A-Z]{2}|[A-Z][A-Za-z]{2,30})$/);
      if (m) { out.location = seg; break; }
    }
    if (out.location) break;
  }

  // Education + certifications: walk the named sections. A "section header" is
  // a short line that is (or starts with) the section word — markdown #'s,
  // ALL-CAPS, or plain. The section ends at the next header-looking line.
  const sectionLines = (name) => {
    const re = new RegExp(`^#*\\s*${name}\\b[\\s:]*$`, 'i');
    // ALL-CAPS header detection must be case-SENSITIVE — under /i it would
    // swallow any short mixed-case line ("Master of Business Administration").
    const capsHeader = /^[A-Z][A-Z &/]{3,40}$/;
    const namedHeader = /^#{1,3}\s+\S|^(education|experience|work experience|employment|skills|projects|certifications?|licenses|summary|profile|awards|publications|languages|interests)\b[\s:]*$/i;
    const start = lines.findIndex(l => re.test(l.replace(/\*+/g, '').trim()));
    if (start === -1) return [];
    const got = [];
    for (const raw of lines.slice(start + 1)) {
      const l = raw.replace(/\*+/g, '').trim();
      if (capsHeader.test(l) || namedHeader.test(l)) break;
      if (l) got.push(l.replace(/^[-•▪]\s*/, ''));
      if (got.length >= 12) break;
    }
    return got;
  };

  // Education: pair a degree-looking line with the org/date around it.
  const degreeRe = /\b(B\.?\s?(Sc|S|A|Eng|Com)|M\.?\s?(Sc|S|A|BA|Eng)|MBA|Ph\.?D|Bachelor|Master|Doctor|Diploma|Associate)\b/i;
  const dateRe = /((19|20)\d{2})\s*[–—-]\s*((19|20)\d{2}|present)|\b(19|20)\d{2}\b/i;
  const eduLines = sectionLines('education');
  for (let i = 0; i < eduLines.length && out.education.length < 3; i++) {
    if (!degreeRe.test(eduLines[i])) continue;
    // formats: "Degree — Org (dates)" on one line, or degree line followed by org line
    const line = eduLines[i];
    const entry = { degree: '', org: '', date: '' };
    const dm = line.match(dateRe);
    if (dm) entry.date = dm[0];
    const parts = line.replace(dateRe, '').split(/\s+[–—|·]\s+|,\s+(?=[A-Z])/).map(s => s.trim().replace(/[()]/g, '')).filter(Boolean);
    entry.degree = parts[0] || line;
    if (parts.length > 1) entry.org = parts.slice(1).join(', ');
    else if (eduLines[i + 1] && !degreeRe.test(eduLines[i + 1])) {
      const next = eduLines[i + 1];
      const ndm = next.match(dateRe);
      if (ndm && !entry.date) entry.date = ndm[0];
      entry.org = next.replace(dateRe, '').replace(/\s+[–—|·]\s*$/, '').trim();
      i++;
    }
    out.education.push(entry);
  }

  // Certifications: each non-empty section line is one cert; split "Title — Org".
  for (const l of sectionLines('certifications?|licenses( & certifications)?')) {
    if (out.certifications.length >= 8) break;
    const parts = l.split(/\s+[–—|·]\s+|,\s+(?=[A-Z][a-z])/).map(s => s.trim()).filter(Boolean);
    out.certifications.push({ title: parts[0] || l, org: parts.slice(1).join(', ') });
  }

  return out;
}

// ── kebabCase (used for derived resume PDF filenames) ──────────────────────

export function kebabCase(s) {
  return String(s || '').toLowerCase()
    .normalize('NFKD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim().replace(/\s+/g, '-');
}

// ── parseProfileSummary ─────────────────────────────────────────────────────
// Read the few fields the wizard's "detect-existing-profile" banner needs out
// of a profile.yml string. Line-walking parser (regex was too brittle for
// nested arrays; see commit history). Returns { exists, full_name, email,
// target_roles, substantive }.

export function parseProfileSummary(yml) {
  if (typeof yml !== 'string' || yml.trim().length === 0) {
    return { exists: false, full_name: '', email: '', target_roles: [], substantive: false };
  }

  // Pull the candidate: block (everything up to the next top-level key)
  const candidateBlock = yml.match(/^candidate:\s*\n([\s\S]*?)(?=^\S|\Z)/m);
  const scope = candidateBlock ? candidateBlock[1] : yml;
  const get = (key) => {
    const m = scope.match(new RegExp(`^\\s+${key}:\\s*"?([^"\\n]+?)"?\\s*$`, 'm'));
    return m ? m[1].trim() : '';
  };

  const target_roles = [];
  const lines = yml.split('\n');
  let inTargetRoles = false, inPrimary = false;
  for (const line of lines) {
    if (/^target_roles:\s*$/.test(line)) { inTargetRoles = true; continue; }
    if (inTargetRoles && /^\S/.test(line)) { inTargetRoles = false; inPrimary = false; }
    if (!inTargetRoles) continue;
    if (/^\s+primary:\s*$/.test(line)) { inPrimary = true; continue; }
    // any sibling key under target_roles (e.g. `archetypes:`) ends primary
    if (inPrimary && /^\s+\w+:/.test(line)) inPrimary = false;
    if (!inPrimary) continue;
    const m = line.match(/^\s+-\s+"([^"]+)"/);
    if (m) target_roles.push(m[1]);
  }

  const full_name = get('full_name');
  const email = get('email');
  return {
    exists: true,
    full_name,
    email,
    target_roles,
    substantive: !!(full_name && target_roles.length),
  };
}
